#k:(空格)v：表示一对键值对（空格必须有）
#以空格的缩进来控制层级关系；只要是左对齐的一列数据，都是同一个层级的
#属性和值也是大小写敏感；
#​	k: v：字面直接来写；
#
#  ​		字符串默认不用加上单引号或者双引号；
#
#  ​		""：双引号；不会转义字符串里面的特殊字符；特殊字符会作为本身想表示的意思
#
#​				name:   "zhangsan \n lisi"：输出；zhangsan 换行  lisi
#
#  ​		''：单引号；会转义特殊字符，特殊字符最终只是一个普通的字符串数据
#
#​				name:   ‘zhangsan \n lisi’：输出；zhangsan \n  lisi
server:
    port: 8080
    path: /hello
